#端口号
server:
  port: 9088
#配置服务名
spring:
  application:
    name: studyModel01

#eureka配置
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
